# Generated by Django 3.1.3 on 2021-12-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='is_mutual',
            field=models.BooleanField(default=False),
        ),
    ]
