# Generated by Django 3.1.3 on 2021-12-03 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendships', '0002_friendship_is_mutual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendship',
            options={'ordering': ('-created_at',)},
        ),
    ]
